---
name: ci
on:
  push:
    branches:
      - mainline
jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker buildx create --use
      - run: docker buildx build . -t ajchili/visum:latest --platform linux/amd64,linux/arm64 --push